### PR TITLE
fix: cleanup deny.toml and delete docker-compose.yml

### PR DESCRIPTION
**Pull request by Manuthor**

### CODE REVIEW

**Review by HatemMn — CHANGES_REQUESTED** [review]
No problems on my end

I want to just point it this recurrent issue to maybe fix it for good here : 
image

As we said earlier this command runs it fine `cargo +nightly fmt --all `
image

After reconsideration I think it's better to setup either for stable OR nightly channel for both compiling and formatting, this will make workflows less ambigious, what do you think ?

I sollicite @tbrezot opinion too on the matter

**Comment by Manuthor** [comment]
> No problems on my end
> 
> I want to just point it this recurrent issue to maybe fix it for good here : image
> 
> As we said earlier this command runs it fine `cargo +nightly fmt --all ` image
> 
> After reconsideration I think it's better to setup either for stable OR nightly channel for both compiling and formatting, this will make workflows less ambigious, what do you think ?
> 
> I sollicite @tbrezot opinion too on the matter

Let's remove the `.rustfmt.toml`. 
IMHO, formatting can't drive the choice of the toolchain version.

**Review by tbrezot — APPROVED** [review]

**Comment by tbrezot** [comment]
agrees with @Manuthor here: toolchain must be stable, and formatting requirements getting one the way must be removed

**Review by HatemMn — APPROVED** [review]
@Manuthor I let you delete the file as you and theophile said, you can directly rebase the branch after that

**Pull request merged**
